const {test}=require('node:test');
const assert=require('node:assert/strict');
const C=require('./game-core.js');
function arena(){const s=C.create(()=>.5);s.spawn=s.elite=s.boss=s.gate=s.crate=10000;return s;}
function run(s,seconds,target=500){for(let i=0;i<seconds*60&&!s.over;i++)C.step(s,1/60,typeof target==='function'?target(s):target);}
test('建立狀態即提供干擾與火控公開契約',()=>{const s=C.create();assert.equal(s.jammed,false);assert.deepEqual(s.jamSources,[]);assert.deepEqual(s.fireControl,[]);});
test('支援事件記錄直接命中、砲座與邊界外目標',()=>{const s=C.setup(arena());s.x=500;const normal=C.spawnEnemy(s,'normal',500,300),outside=C.spawnEnemy(s,'normal',690,300),boss=C.spawnSpecial(s,'dinosauria',500,460);boss.intro=0;normal.hp=20;assert.ok(C.useTactic(s));const event=s.events.find(e=>e.type==='tactic');assert.equal(event.width,380);assert.deepEqual(event.hits.map(h=>h.id),[normal.id,boss.id]);assert.deepEqual(event.hits[0],{id:normal.id,kind:'normal',model:'normal',x:500,y:300,part:false,partIndex:null,damage:20,killed:true});assert.deepEqual(event.hits[1],{id:boss.id,kind:'boss',model:'dinosauria',x:605,y:460,part:true,partIndex:1,damage:190,killed:false});assert.equal(outside.hp,outside.max);});
test('支援取消只回報本次真正移除的未發射危險區，空放仍有空陣列',()=>{const s=C.setup(arena());s.x=500;s.hazards=[{source:1,model:'artillery',kind:'mortar',x:500,y:805,fired:false},{source:2,model:'morpho',kind:'rail',x:500,y:480,fired:true},{source:3,model:'shield',kind:'shell',x:800,y:300,fired:false}];C.useTactic(s);let event=s.events.find(e=>e.type==='tactic');assert.deepEqual(event.cancelled.map(h=>h.source),[1]);assert.equal(s.hazards.length,2);s.charges=1;s.tacticCooldown=0;s.events=[];C.useTactic(s);event=s.events.find(e=>e.type==='tactic');assert.deepEqual(event.hits,[]);assert.deepEqual(event.cancelled,[]);});
test('誘餌事件與危險區鎖定誘導位置，過期後不再標記新攻擊',()=>{const s=C.setup(arena(),{tactic:'decoy'});s.x=420;C.useTactic(s);let event=s.events.find(e=>e.type==='tactic');assert.equal(event.duration,4);assert.deepEqual(s.decoy,{x:420,y:770,life:4});const artillery=C.spawnSpecial(s,'artillery',500,240);artillery.cooldown=0;C.specialEnemy(s,artillery,.01);assert.equal(s.hazards[0].decoyX,420);s.hazards=[];const morpho=C.spawnSpecial(s,'morpho',500,460);morpho.intro=0;morpho.cooldown=0;morpho.attackCount=1;C.specialEnemy(s,morpho,.01);assert.ok(s.hazards.every(h=>h.kind==='vulcan'&&h.decoyX===420));s.decoy.life=.01;C.step(s,.02,700);s.hazards=[];morpho.cooldown=0;C.specialEnemy(s,morpho,.01);assert.ok(s.hazards.every(h=>h.decoyX===undefined));});
test('僚機與主機耐久有上限',()=>{const s=C.create();assert.equal(s.count,2);C.recruit(s,100);assert.equal(s.count,4);s.shield=95;C.collect(s,{kind:'shield',readable:true,y:815});assert.equal(s.shield,100);});
test('永久火力有限，不再讓每個人同時取得三散射三貫穿',()=>{assert.deepEqual(C.weapon(100),C.weapon(8));assert.equal(C.weapon(4).spread,1);assert.ok(C.weapon(8).interval>=.15);});
test('主砲初始單發可清雜兵，成長不參考玩家人數',()=>{const s=arena(),e=C.spawnEnemy(s,'normal',500,200);C.damageEnemy(s,e,C.weapon(0).damage);assert.ok(e.dead);assert.ok(C.difficulty(120).health>C.difficulty(0).health);});
test('壓力有高峰及喘息，之後的強度增加',()=>{assert.ok(C.difficulty(15).density>C.difficulty(24).density);assert.ok(C.difficulty(120).speed>C.difficulty(0).speed);});
test('Boss 初登場有預警，四秒內會發射第一招',()=>{const s=arena();s.shot=10000;const b=C.spawnEnemy(s,'boss',500,280);run(s,.5);assert.equal(s.hazards.length,0);run(s,3.5,110);assert.ok(b.attackCount>=1);assert.ok(s.stats.bossShots>=1);assert.equal(C.spawnEnemy(s,'boss',500),null);});
test('Boss 重砲優先損失一架僚機，同一射界不連續清空隊伍',()=>{const s=arena();s.count=3;s.shield=8;s.hazards.push({source:99,kind:'rail',x:500,y:300,width:230,delay:.01,maxDelay:1,life:.22,damage:999,lethal:true});run(s,.3);assert.equal(s.count,2);assert.equal(s.hp,100);assert.equal(s.shield,8);assert.equal(s.over,false);});
test('獨機承受重砲45傷害仍可由裝甲吸收，不以滿血強制結束',()=>{const s=arena();s.count=1;s.shield=20;C.hurt(s,999,true,{kind:'rail',model:'morpho'});assert.equal(s.hp,75);assert.equal(s.shield,0);assert.equal(s.over,false);s.invulnerable=0;s.hp=40;C.hurt(s,999,true,{kind:'rail',model:'morpho'});assert.equal(s.over,true);assert.equal(s.count,0);});
test('重砲尊重受擊保護，交錯射界不連續剝除僚機',()=>{const s=arena();s.count=3;C.hurt(s,999,true,{kind:'sweep'});C.hurt(s,999,true,{kind:'rail'});assert.equal(s.count,2);assert.equal(s.events.filter(e=>e.type==='hurt').length,1);});
test('致命區域判斷與顯示採小隊中心，不誤殺區域外士兵',()=>{const s=arena();s.x=s.target=700;s.hazards.push({source:99,kind:'rail',x:500,y:300,width:230,delay:.01,maxDelay:1,life:.22,lethal:true});C.step(s,.02,700);assert.ok(!s.over);});
test('Boss 三種招式都有可達的安全通路',()=>{for(const x of [110,500,890])for(let turn=0;turn<3;turn++){const s=arena();s.x=x;s.shot=10000;const b=C.spawnEnemy(s,'boss',500,280);b.intro=0;b.cooldown=0;b.attackCount=turn;C.step(s,.01,x);assert.ok(s.hazards.length);const safe=[];for(let p=110;p<=890;p+=10)if(s.hazards.every(h=>Math.abs(p-h.x)>h.width/2+18))safe.push(p);assert.ok(safe.length);const time=Math.min(...s.hazards.map(h=>h.delay));assert.ok(safe.some(p=>Math.abs(p-x)/720+.22<time),`不可逃離: ${x}, ${turn}`);}});
test('弱點只取消未發射砲擊且短暫打斷，不能無限控場',()=>{const s=arena();const b=C.spawnEnemy(s,'boss',500,280);b.intro=0;s.hazards=[{source:b.id,fired:true},{source:b.id,fired:false}];C.hitBossNode(s,b,0,10000);assert.equal(s.hazards.length,1);assert.ok(b.exposed<=1.6);assert.ok(b.cooldown<=1);});
test('三種精英都能主動出招',()=>{for(const type of ['scout','shield','charger']){const s=arena();s.shot=10000;const e=C.spawnEnemy(s,type,500,350);run(s,2,110);assert.ok(e.attackCount>0,type);}});
test('斥候被擊破能取消標定；突擊鎖定後不追蹤',()=>{const s=arena();s.shot=10000;const e=C.spawnEnemy(s,'scout',500,300);e.cooldown=0;C.step(s,.01,500);assert.ok(s.hazards.length);C.damageEnemy(s,e,99999);assert.equal(s.hazards.length,0);const c=C.spawnEnemy(s,'charger',500,450);c.cooldown=0;C.step(s,.01,300);const locked=c.chargeX;run(s,.2,850);assert.equal(c.chargeX,locked);});
test('同組道具只能拿一個，EMP 有實際清場及打斷效果',()=>{const s=arena();const e=C.spawnEnemy(s,'normal',500,500);s.hazards.push({source:99,fired:false});const a={id:1,group:4,kind:'emp',hp:1,readable:true,y:815},b={id:2,group:4,kind:'shield',hp:1,readable:true,y:815};s.crates=[a,b];C.collect(s,a);assert.ok(e.dead);assert.equal(s.hazards.length,0);assert.ok(a.used&&b.used);const old=s.shield;C.collect(s,b);assert.equal(s.shield,old);});
test('死亡當幀不再吃增援，重新開始完整重置',()=>{const s=arena();s.hp=1;s.shot=10000;C.spawnEnemy(s,'normal',500,806);s.gates.push({id:99,x:500,y:803,hits:0,base:2});C.step(s,.02,500);assert.ok(s.over);assert.equal(s.count,0);assert.equal(C.create().count,2);});
test('普通接觸保護避免同幀重複傷害',()=>{const s=C.create();s.shield=3;C.hurt(s,5);assert.equal(s.hp,98);C.hurt(s,5);assert.equal(s.hp,98);});
test('子彈不會收取或破壞補給',()=>{const s=arena(),box={id:1,x:500,y:700,kind:'repair',hp:1,max:1,readable:true};s.crates=[box];s.bullets=[{x:500,px:500,y:700,py:720,vx:0,damage:999,life:1,left:1,hit:[]}];C.step(s,.01,500);assert.equal(box.used,undefined);assert.equal(box.hp,1);});
test('主機跨越補給線只選一次，中央可略過',()=>{const s=arena();s.x=265;const a={id:1,group:2,x:265,y:815,kind:'repair',readable:true},b={id:2,group:2,x:735,y:815,kind:'weapon',readable:true};s.crates=[a,b];s.hp=50;C.step(s,.01,265);assert.equal(s.hp,80);assert.equal(a.used,true);assert.equal(b.used,true);const items=s.stats.items;C.step(s,.01,265);assert.equal(s.stats.items,items);const t=C.create(),c={id:1,group:2,x:265,y:815,kind:'repair',readable:true},d={id:2,group:2,x:735,y:815,kind:'weapon',readable:true};t.crates=[c,d];C.step(t,.01,500);assert.equal(c.used,true);assert.equal(d.used,true);assert.equal(t.stats.items,0);});
test('Boss 擊破立即結束並發出勝利事件',()=>{const s=arena();const b=C.spawnEnemy(s,'boss',500,280);C.damageEnemy(s,b,99999);assert.ok(s.won&&s.over);assert.ok(s.events.some(e=>e.type==='won'));});
test('編隊砲口使用 formation，主砲與機槍分開計時',()=>{const s=arena();s.shot=0;s.mg=0;s.x=500;C.step(s,.01,500);const formation=C.formation(s),main=s.bullets.filter(b=>b.shell),mg=s.bullets.filter(b=>!b.shell);assert.equal(main.length,formation.length);assert.equal(mg.length,formation.length);assert.ok(s.events.includes({type:'mainShot'})||s.events.some(e=>e.type==='mainShot'));s.bullets=[];s.shot=1;s.mg=0;C.step(s,.01,500);assert.equal(s.bullets.filter(b=>b.shell).length,0);assert.ok(s.bullets.length>0);});
test('斥候與Löwe聯動，任一被擊破可取消未發射砲擊，已發射不可取消',()=>{const s=arena();s.shot=10000;const scout=C.spawnEnemy(s,'scout',400,300),tank=C.spawnEnemy(s,'shield',600,300);scout.cooldown=0;C.step(s,.01,500);assert.ok(s.hazards.length);const h=s.hazards[0];C.damageEnemy(s,scout,9999);assert.equal(s.hazards.filter(x=>!x.fired).length,0);scout.dead=false;scout.hp=70;s.hazards=[{source:tank.id,linkedTo:scout.id,fired:true,life:.3}];C.damageEnemy(s,scout,9999);assert.equal(s.hazards.length,1);});
test('補給接近選取線時不啟動Boss致命蓄力',()=>{const s=arena();const b=C.spawnEnemy(s,'boss',500,280);b.intro=0;b.cooldown=0;s.crates=[{id:1,x:500,y:600,kind:'repair',readable:true,used:false}];C.step(s,.01,500);assert.equal(s.hazards.filter(h=>h.lethal&&!h.fired).length,0);});

test('三機型實際速度、耐久與停穩破甲不同',()=>{const light=C.setup(arena(),{machine:'m1a4'}),heavy=C.setup(arena(),{machine:'m4a3'}),fast=C.setup(arena(),{machine:'xm2'});for(const s of [light,heavy,fast]){s.special=s.boss=10000;run(s,.3,890);}assert.ok(fast.x>light.x&&light.x>heavy.x);assert.equal(heavy.maxHp,160);assert.equal(fast.maxHp,80);heavy.x=heavy.target=500;heavy.shot=0;heavy.brace=.5;C.step(heavy,.01,500);assert.ok(heavy.bullets.some(b=>b.shell&&b.armorPiercing));});
test('支援由玩家主動使用、扣次數並阻止連按',()=>{const s=C.setup(arena());s.special=10000;const e=C.spawnEnemy(s,'shield',500,300);assert.ok(C.useTactic(s));assert.equal(e.hp,e.max-230);assert.equal(s.charges,0);assert.equal(C.useTactic(s),false);});
test('誘餌記住放置位置，離開後吸引下一次砲擊',()=>{const s=C.setup(arena(),{tactic:'decoy'});s.special=10000;C.useTactic(s);s.x=800;const e=C.spawnEnemy(s,'shield',500,300);C.telegraph(s,e,'shell',s.x,150,1,30);assert.equal(s.hazards[0].x,500);});
test('地雷被射爆連鎖傷害附近軍團',()=>{const s=arena(),mine=C.spawnSpecial(s,'mine',500,400),victim=C.spawnSpecial(s,'mine',590,400),other=C.spawnEnemy(s,'normal',660,420);C.damageEnemy(s,mine,100);assert.ok(mine.dead&&victim.dead&&other.dead);});
test('砲兵留下爆區，斥候存活才增加第二落點',()=>{const s=arena();s.shot=s.mg=10000;const e=C.spawnSpecial(s,'artillery',500,240);e.cooldown=0;C.specialEnemy(s,e,.01);assert.equal(s.hazards.length,1);assert.ok(s.hazards[0].persistent);s.hazards=[];e.cooldown=0;const scout=C.spawnEnemy(s,'scout',700,300);C.specialEnemy(s,e,.01);assert.equal(s.hazards.length,2);C.damageEnemy(s,scout,9999);assert.equal(s.hazards.length,1);});
test('砲兵與斥候協同砲擊在最後 .45 秒才由真正砲兵發射，傷害與總延遲不變',()=>{const s=arena(),artillery=C.spawnSpecial(s,'artillery',300,240),scout=C.spawnEnemy(s,'scout',700,300),seen=[];s.shot=s.mg=10000;artillery.cooldown=0;C.specialEnemy(s,artillery,.01);assert.deepEqual(s.hazards.map(h=>[h.delay,h.width,h.damage,h.life,h.volley,h.shotIndex]),[[1.5,190,22,2.2,1,0],[2.1,190,22,2.2,1,1]]);assert.deepEqual(s.events.find(e=>e.type==='mortarAim'),{type:'mortarAim',sourceId:artillery.id,volley:1,linkedTo:scout.id,x:300,y:240});for(let i=0;i<64;i++){C.step(s,1/60,500);seen.push(...s.events);}const launch=seen.find(e=>e.type==='mortarLaunch');assert.equal(launch.sourceId,artillery.id);assert.equal(launch.fromX,300);assert.ok(Math.abs(launch.duration-.45)<.02);assert.ok(!seen.some(e=>e.type==='cannon'&&e.kind==='mortar'));for(let i=0;i<28;i++){C.step(s,1/60,500);seen.push(...s.events);}assert.ok(seen.some(e=>e.type==='mortarImpact'&&e.shotIndex===0));assert.equal(s.hp,78);});
test('斥候與支援或 EMP 只取消未發射的協同砲擊，空中砲彈仍會命中',()=>{const s=arena(),artillery=C.spawnSpecial(s,'artillery',300,240),scout=C.spawnEnemy(s,'scout',700,300);s.shot=s.mg=10000;artillery.cooldown=0;C.specialEnemy(s,artillery,.01);for(let i=0;i<64;i++)C.step(s,1/60,500);C.damageEnemy(s,scout,9999);assert.equal(s.hazards.length,1);assert.ok(s.hazards[0].launched);assert.deepEqual(s.events.find(e=>e.type==='fireLinkBroken').cancelled.map(h=>h.shotIndex),[1]);s.charges=1;s.x=500;C.useTactic(s);assert.ok(s.hazards[0].launched);C.collect(s,{kind:'emp',readable:true,y:815});assert.ok(s.hazards[0].launched);run(s,.45,500);assert.equal(s.hp,78);});
test('干擾只改自動鎖定，離開或擊破後解除',()=>{const s=C.setup(arena());s.special=10000;const e=C.spawnSpecial(s,'jammer',500,320);C.step(s,.01,500);assert.equal(s.jammed,true);s.x=110;C.step(s,.01,110);assert.equal(s.jammed,false);s.x=500;C.damageEnemy(s,e,9999);C.step(s,.01,500);assert.equal(s.jammed,false);});
test('干擾快照與轉換事件只在狀態改變時反映真正來源',()=>{const s=C.setup(arena());s.special=10000;const a=C.spawnSpecial(s,'jammer',500,320),b=C.spawnSpecial(s,'jammer',540,320);s.shot=s.mg=10000;C.step(s,.01,500);let change=s.events.find(e=>e.type==='jamChange');assert.deepEqual(change.sources.map(e=>e.id),[a.id,b.id]);assert.equal(change.reason,'entered');C.damageEnemy(s,a,999);C.step(s,.01,500);assert.equal(s.events.some(e=>e.type==='jamChange'),false);assert.deepEqual(s.jamSources.map(e=>e.id),[b.id]);s.x=110;C.step(s,.01,110);change=s.events.find(e=>e.type==='jamChange');assert.equal(change.reason,'left');assert.deepEqual(change.previousSources.map(e=>e.id),[b.id]);s.x=500;C.step(s,.01,500);C.damageEnemy(s,b,999);C.step(s,.01,500);change=s.events.find(e=>e.type==='jamChange');assert.equal(change.reason,'destroyed');});
test('干擾火控讓遠距砲彈直射，近距仍依真目標偏轉並在離開後恢復',()=>{const s=C.setup(arena());s.special=10000;s.x=s.target=500;s.shot=0;s.mg=10000;const e=C.spawnEnemy(s,'normal',600,400);e.speed=0;C.step(s,.01,500);assert.equal(s.fireControl[0].target.id,e.id);assert.ok(s.bullets.find(b=>b.shell).vx>0);s.bullets=[];s.shot=0;const jammer=C.spawnSpecial(s,'jammer',500,320);C.step(s,.01,500);assert.equal(s.fireControl[0].target,null);assert.equal(s.bullets.find(b=>b.shell).vx,0);s.bullets=[];s.shot=0;e.y=600;C.step(s,.01,500);assert.equal(s.fireControl[0].target.id,e.id);assert.ok(s.bullets.find(b=>b.shell).vx>0);s.x=110;s.target=110;e.x=180;s.bullets=[];s.shot=0;C.step(s,.01,110);assert.equal(s.jammed,false);assert.equal(s.fireControl[0].target.id,e.id);assert.ok(s.bullets.find(b=>b.shell).vx>0);C.damageEnemy(s,jammer,999);});
test('Dinosauria主砲發射後才開啟反擊窗口',()=>{const s=arena();s.shot=s.mg=10000;s.x=110;const e=C.spawnSpecial(s,'dinosauria',500,460);e.intro=0;e.cooldown=0;C.step(s,.01,110);assert.equal(e.exposed,0);assert.ok(s.hazards[0].opensArmor);run(s,1.5,800);assert.ok(e.exposed>2);});
test('Dinosauria每輪重砲後由全部存活側砲固定追射，主砲才可被誘餌改瞄準',()=>{const s=C.setup(arena(),{tactic:'decoy'}),b=C.spawnSpecial(s,'dinosauria',500,460);s.x=500;C.useTactic(s);s.x=740;b.intro=0;b.cooldown=0;C.specialEnemy(s,b,.01);assert.deepEqual(s.hazards.map(h=>[h.kind,h.x,h.width,h.delay,h.damage,h.partIndex,h.volley]),[['heavy',500,280,1.3,40,undefined,1],['secondary',205,260,2.1,24,0,1],['secondary',795,260,2.1,24,1,1]]);assert.equal(s.hazards[0].decoyX,500);assert.equal(s.hazards[1].decoyX,undefined);assert.equal(s.hazards[2].decoyX,undefined);});
test('Dinosauria拆件只取消本側未發砲，保留另一側與已發砲並給反制停頓',()=>{const s=arena(),b=C.spawnSpecial(s,'dinosauria',500,460);s.shot=s.mg=10000;b.intro=0;b.cooldown=0;C.specialEnemy(s,b,.01);run(s,2.12,500);assert.ok(s.hazards.some(h=>h.kind==='secondary'&&h.partIndex===0&&h.fired));C.hitBossNode(s,b,0,999);assert.equal(b.partDisabled[0],true);assert.ok(b.cooldown>=2.2);assert.ok(s.hazards.some(h=>h.kind==='secondary'&&h.partIndex===0&&h.fired));assert.ok(s.hazards.some(h=>h.kind==='secondary'&&h.partIndex===1));assert.ok(!s.hazards.some(h=>h.kind==='secondary'&&h.partIndex===0&&!h.fired));});
test('Dinosauria單側殘存只保留該翼追射，雙翼全毀維持單發重砲',()=>{const s=arena(),b=C.spawnSpecial(s,'dinosauria',500,460);b.intro=0;C.hitBossNode(s,b,0,999);b.cooldown=0;C.specialEnemy(s,b,.01);assert.deepEqual(s.hazards.map(h=>[h.kind,h.partIndex]),[['heavy',undefined],['secondary',1]]);s.hazards=[];C.hitBossNode(s,b,1,999);b.cooldown=0;C.specialEnemy(s,b,.01);assert.deepEqual(s.hazards.map(h=>[h.kind,h.delay,h.damage,h.partIndex]),[['heavy',1.25,52,undefined]]);});
test('Dinosauria重砲實射才發出反攻事件，砲火事件保留砲座與射界資料',()=>{const s=arena(),b=C.spawnSpecial(s,'dinosauria',500,460),seen=[];s.shot=s.mg=10000;s.x=110;b.intro=0;b.cooldown=0;C.specialEnemy(s,b,.01);for(let i=0;i<45;i++){C.step(s,.05,110);seen.push(...s.events);}const cannon=seen.filter(e=>e.type==='cannon'&&e.model==='dinosauria');assert.deepEqual(cannon.map(e=>[e.kind,e.partIndex,e.width,e.volley]),[['heavy',null,280,1],['secondary',0,260,1],['secondary',1,260,1]]);assert.deepEqual(seen.filter(e=>e.type==='bossRecovery'&&e.model==='dinosauria').map(e=>e.duration),[2.5]);});
test('最慢M4A3能在重砲前離開中央並在雙翼追射前回中央，不靠受擊保護',()=>{const s=C.setup(arena(),{machine:'m4a3'}),b=C.spawnSpecial(s,'dinosauria',500,460);s.special=s.boss=10000;s.shot=s.mg=10000;s.x=s.target=500;b.intro=0;b.cooldown=0;C.specialEnemy(s,b,.01);run(s,2.25,state=>state.time<1.35?350:500);assert.equal(s.hp,s.maxHp);assert.equal(s.stats.hits||0,0);});
test('正常步進會讓Dinosauria完成一輪追射，且側移自動砲火可拆掉砲座',()=>{const s=C.setup(arena(),{encounter:'dinosauria',ammo:'ap'}),b=C.spawnSpecial(s,'dinosauria',500,460);s.spawn=s.boss=s.special=s.crate=s.elite=s.gate=10000;s.x=s.target=395;b.intro=0;b.cooldown=0;run(s,7,395);assert.ok(b.attackCount>0);assert.equal(b.nodes[0],0);assert.ok(b.partDisabled[0]);});
test('Morpho安全缺口對最慢M4A3也可達，且沒有全場封死',()=>{for(const x of [110,500,890])for(const turn of [0,2,4]){const s=C.setup(arena(),{machine:'m4a3'});s.special=10000;s.x=x;const e=C.spawnSpecial(s,'morpho',500,460);e.intro=0;e.cooldown=0;e.attackCount=turn;C.specialEnemy(s,e,.01);assert.equal(s.hazards.length,2);assert.ok(s.hazards.every(h=>Math.abs(e.gap-h.x)>h.width/2));assert.ok(Math.abs(x-e.gap)/s.speed+.3<s.hazards[0].delay);}});
test('Morpho軌道砲實際發射後只開一次反擊窗口',()=>{const s=arena(),b=C.spawnSpecial(s,'morpho',500,460);s.shot=s.mg=10000;b.intro=0;b.cooldown=0;C.specialEnemy(s,b,.01);assert.equal(b.exposed,0);assert.equal(s.events.filter(e=>e.type==='bossRecovery').length,0);run(s,1.91,500);assert.equal(s.events.filter(e=>e.type==='bossRecovery').length,1);const event=s.events.find(e=>e.type==='bossRecovery');assert.equal(event.sourceId,b.id);assert.equal(event.model,'morpho');assert.equal(event.duration,2.2);assert.ok(b.exposed>2);});
test('Morpho被破件取消蓄力時不會虛開反擊窗口',()=>{const s=arena(),b=C.spawnSpecial(s,'morpho',500,460);b.intro=0;b.cooldown=0;C.specialEnemy(s,b,.01);C.hitBossNode(s,b,0,999);assert.ok(b.cooldown>=2.2);run(s,2.1,500);assert.equal(s.events.filter(e=>e.type==='bossRecovery').length,0);});
test('Morpho三連火神砲鎖定落點且破損砲座取消未發射砲彈',()=>{const s=arena(),b=C.spawnSpecial(s,'morpho',500,460);b.intro=0;b.cooldown=0;b.attackCount=1;s.x=190;C.specialEnemy(s,b,.01);const hazards=s.hazards.filter(h=>h.kind==='vulcan');assert.deepEqual(hazards.map(h=>h.x),[190,360,530]);assert.deepEqual(hazards.map(h=>+h.delay.toFixed(1)),[.9,1.3,1.7]);assert.deepEqual(hazards.map(h=>h.width),[140,140,140]);const locked=hazards.map(h=>h.x);s.x=850;run(s,.95,850);assert.deepEqual(s.hazards.filter(h=>!h.fired).map(h=>h.x),locked.slice(1));const pending=s.hazards.find(h=>!h.fired);C.hitBossNode(s,b,pending.partIndex,999);run(s,1,850);assert.ok(!s.events.some(e=>e.type==='cannon'&&e.volley===b.attackCount&&e.fromX===b.x+(pending.partIndex?105:-105)));});
test('Morpho火神砲只使用存活砲座，全毀改用窄幅主砲且修復後恢復三連射',()=>{const s=arena(),b=C.spawnSpecial(s,'morpho',500,460);b.intro=0;b.cooldown=0;b.attackCount=1;C.hitBossNode(s,b,0,999);b.cooldown=0;C.specialEnemy(s,b,.01);assert.deepEqual(s.hazards.map(h=>h.partIndex),[1,1,1]);s.hazards=[];C.hitBossNode(s,b,1,999);b.attackCount=1;b.cooldown=0;C.specialEnemy(s,b,.01);assert.deepEqual(s.hazards.map(h=>h.kind),['rail']);assert.equal(b.attackCount,2);assert.ok(b.cooldown>=3.4);s.hazards=[];b.cooldown=0;C.specialEnemy(s,b,.01);assert.deepEqual(s.hazards.map(h=>h.kind),['sweep','sweep']);s.hazards=[];b.nodeRepair=0;C.specialEnemy(s,b,.01);b.cooldown=0;C.specialEnemy(s,b,.01);assert.equal(s.hazards.length,3);assert.deepEqual([...new Set(s.hazards.map(h=>h.partIndex))],[1,0]);});
test('Morpho本體裝甲與反擊窗口使用真正砲彈傷害',()=>{const s=arena(),b=C.spawnSpecial(s,'morpho',500,460);s.shot=s.mg=10000;b.intro=0;b.cooldown=100;b.y=460;const fire=()=>{s.bullets.push({x:500,y:468,px:500,py:468,vx:0,damage:100,life:1,left:1,shell:true,controlled:true,hit:[]});C.step(s,.01,500);};const hp=b.hp;fire();assert.equal(hp-b.hp,50);b.exposed=2.2;const exposedHp=b.hp;fire();assert.equal(exposedHp-b.hp,220);});
test('混合戰擊破首個Boss後繼續，第二個Boss才勝利',()=>{const s=C.setup(arena());const first=C.spawnSpecial(s,'dinosauria',500,460);C.damageEnemy(s,first,99999);assert.equal(s.over,false);assert.equal(s.stage,1);assert.equal(s.events.find(e=>e.type==='objective').model,'morpho');s.enemies=[];const last=C.spawnSpecial(s,'morpho',500,460);C.damageEnemy(s,last,99999);assert.equal(s.won,true);});
test('Dinosauria部件永久破壞且已發射砲擊不被取消',()=>{const s=arena(),b=C.spawnSpecial(s,'dinosauria',500,460);b.intro=0;s.hazards=[{source:b.id,fired:true,kind:'secondary',partIndex:0},{source:b.id,fired:false,kind:'secondary',partIndex:0}];C.hitBossNode(s,b,0,9999);assert.equal(b.nodes[0],0);assert.equal(b.partDisabled[0],true);assert.equal(s.hazards.length,1);assert.equal(s.hazards[0].fired,true);assert.ok(s.events.some(e=>e.type==='partBreak'&&e.index===0));});
test('charger閃避後退回砲口前才失衡並可被反擊',()=>{const s=arena(),c=C.spawnEnemy(s,'charger',500,780);c.dashing=true;c.chargeX=500;s.x=800;C.step(s,.05,800);assert.equal(c.y,795);assert.equal(c.retreat,true);while(c.retreat)C.step(s,.01,800);assert.ok(c.stagger>0);assert.equal(c.y,Math.min(680,(s.muzzleY??690)-40));assert.ok(s.events.some(e=>e.type==='stagger'));C.damageEnemy(s,c,9999);assert.ok(c.dead);});
test('支援從玩家所在側拆除Dinosauria部件',()=>{const s=C.setup(arena());s.charges=1;s.x=350;const b=C.spawnSpecial(s,'dinosauria',500,460);b.intro=0;assert.ok(C.useTactic(s));assert.equal(b.nodes[0],0);assert.equal(b.nodes[1],190);assert.ok(s.events.some(e=>e.type==='partBreak'&&e.source==='support'));});

test('獵兵必須抵達命中線才傷害，側移可閃且失衡增傷',()=>{for(const x of [500,800]){const s=arena();s.shot=s.mg=s.blade=10000;s.x=x;const c=C.spawnEnemy(s,'charger',500,675);c.dashing=true;c.chargeX=500;C.step(s,.02,x);assert.equal(s.hp,100);run(s,.5,x);assert.equal(s.hp,x===500?65:100);assert.equal(!!c.stagger,x!==500);if(c.stagger){const hp=c.hp;C.damageEnemy(s,c,10);assert.equal(c.hp,hp-18);}}});
test('拆除左砲座後只發射右副砲，兩側拆除後只用主砲',()=>{const s=arena();s.shot=s.mg=10000;const b=C.spawnSpecial(s,'dinosauria',500,460);b.intro=0;C.hitBossNode(s,b,0,999);for(let i=0;i<6;i++){s.hazards=[];b.cooldown=0;C.specialEnemy(s,b,.01);assert.ok(s.hazards.length);assert.ok(s.hazards.every(h=>h.partIndex!==0));}C.hitBossNode(s,b,1,999);s.hazards=[];b.cooldown=0;C.specialEnemy(s,b,.01);assert.deepEqual(s.hazards.map(h=>h.kind),['heavy']);assert.ok(s.hazards[0].damage>=50);});
test('拆左砲保留右砲預告及已發射攻擊',()=>{const s=arena(),b=C.spawnSpecial(s,'dinosauria',500,460);b.intro=0;s.hazards=[{source:b.id,fired:false,partIndex:0},{source:b.id,fired:false,partIndex:1},{source:b.id,fired:true,partIndex:0}];C.hitBossNode(s,b,0,999);assert.equal(s.hazards.length,2);assert.ok(s.hazards.some(h=>h.partIndex===1&&!h.fired));assert.ok(s.hazards.some(h=>h.fired));});

test('主機換到側面才瞄準部件，中央僚機不會自動拆完雙側',()=>{for(const x of [500,395]){const s=C.setup(arena(),{machine:'m1a4',ammo:'ap',encounter:'dinosauria'});s.spawn=s.boss=s.special=s.crate=s.elite=10000;s.x=s.target=x;s.hp=s.maxHp=999;const b=C.spawnSpecial(s,'dinosauria',500,460);b.intro=0;b.cooldown=10000;run(s,7,x);assert.equal(b.nodes[1],190);assert.equal(b.nodes[0],x===500?190:0);}});

test('結算記錄真正致命來源，傷害只計實際耐久損失且重複命中不覆寫',()=>{
 const s=C.create(()=>.5);s.hp=20;
 C.hurt(s,35,false,{kind:'ram',model:'grauwolf',sourceId:7});
 assert.equal(s.stats.damage,20);
 assert.equal(s.lastDamage.model,'grauwolf');
 assert.equal(s.lastDamage.kind,'ram');
 C.hurt(s,999,true,{kind:'rail',model:'morpho',sourceId:8});
 assert.equal(s.lastDamage.sourceId,7);
 assert.equal(s.events.filter(e=>e.type==='over').length,1);
});

test('只有終止的戰鬥能建立不可變結算，後續修改不改變戰績',()=>{
 const s=C.setup(C.create(()=>.5),{machine:'xm2',encounter:'morpho',tactic:'decoy'});
 assert.equal(C.result(s),null);
 s.time=42;s.kills=17;s.count=1;s.hp=30;C.hurt(s,999,true,{kind:'sweep',model:'morpho'});
 const result=C.result(s);s.kills=999;s.lastDamage.kind='unknown';
 assert.equal(result.kills,17);assert.equal(result.machine,'xm2');assert.equal(result.lastDamage.kind,'sweep');
 assert.equal(result.won,false);assert.ok(Object.isFrozen(result));assert.ok(Object.isFrozen(result.lastDamage));
});

test('射界來源在砲手死亡後仍可追溯於結算',()=>{
 const s=C.create(()=>.5);s.spawn=s.elite=s.boss=s.gate=s.crate=999;s.hp=15;
 const e=C.spawnSpecial(s,'morpho',500,460);C.telegraph(s,e,'vulcan',500,180,.1,18);
 e.dead=true;s.enemies=[];C.step(s,.05,500);C.step(s,.05,500);
 assert.equal(s.over,true);assert.equal(s.lastDamage.model,'morpho');assert.equal(s.lastDamage.kind,'vulcan');
});

test('道具回饋保留領取前後真實數值，修復不誇大超出上限的收益',()=>{
 const s=C.setup(C.create(),{machine:'m1a4'});s.hp=95;
 C.collect(s,{kind:'repair',x:265,y:815,readable:true});
 const event=s.events.find(e=>e.type==='item');
 assert.equal(event.before.hp,95);assert.equal(event.after.hp,100);
 s.hp=20;assert.equal(event.after.hp,100);
});

test('滿級火控補給回饋顯示急速裝填，且不虛報等級增加',()=>{
 const s=C.setup(C.create(),{});s.level=8;s.overdrive=0;
 C.collect(s,{kind:'weapon',x:265,y:815,readable:true});
 const event=s.events.find(e=>e.type==='item');
 assert.equal(event.before.level,8);assert.equal(event.after.level,8);assert.equal(event.after.overdrive,6);
});

test('擊毀事件保留專業機型識別，殘骸不退回通用敵機',()=>{
 const s=C.setup(C.create(),{});const e=C.spawnSpecial(s,'artillery',300,420);e.walk=2.7;e.phase=.4;C.damageEnemy(s,e,999);
 const event=s.events.find(event=>event.type==='kill');assert.deepEqual(event,{type:'kill',sourceId:e.id,kind:'artillery',model:'artillery',x:300,y:420});
});

test('Boss命中事件區分砲座與本體，呈現不必重新猜測已被擊毀的部件',()=>{
 const s=C.setup(C.create(()=>.5),{encounter:'dinosauria'});s.enemies=[];s.spawn=s.boss=s.special=s.crate=s.elite=s.gate=10000;s.shot=s.mg=s.blade=10000;
 const e=C.spawnSpecial(s,'dinosauria',500,460);e.intro=0;e.cooldown=10000;e.y=460;
 s.bullets=[{x:395,y:468,px:395,py:468,vx:0,damage:1,life:1,left:1,shell:true,controlled:true,hit:[]}];C.step(s,.01,500);
 const event=s.events.find(event=>event.type==='impact');assert.equal(event.kind,'boss');assert.equal(event.model,'dinosauria');assert.equal(event.part,true);
});


test('Morpho拆除雙側砲後主砲預鎖不追蹤，單發命中非致命且不虛開核心',()=>{const s=arena(),b=C.spawnSpecial(s,'morpho',500,460);s.shot=s.mg=10000;s.x=500;b.intro=0;b.cooldown=0;b.attackCount=1;b.nodes=[0,0];b.nodeRepair=10;C.specialEnemy(s,b,.01);assert.equal(s.hazards.length,1);const h=s.hazards[0];assert.equal(h.kind,'rail');assert.equal(h.lethal,false);assert.equal(h.width,180);assert.equal(h.delay,1.15);assert.equal(h.damage,24);s.x=700;C.step(s,.1,700);assert.equal(h.x,500);s.x=500;run(s,1.12,500);assert.equal(s.hp,76);assert.ok(!s.over);assert.equal(b.exposed,0);assert.equal(s.events.filter(e=>e.type==='bossRecovery').length,0);});
test('Morpho窄幅主砲對最慢機型可躲避，側砲修復只通報一次',()=>{for(const x of [110,500,890]){const s=C.setup(arena(),{machine:'m4a3'}),b=C.spawnSpecial(s,'morpho',500,460);s.special=s.boss=10000;s.shot=s.mg=10000;s.x=x;b.intro=0;b.cooldown=0;b.attackCount=1;b.nodes=[0,0];b.nodeRepair=10;C.specialEnemy(s,b,.01);const h=s.hazards[0],safe=x<500?x+130:x-130;assert.ok(Math.abs(safe-x)/s.speed+.3<h.delay);run(s,1.4,safe);assert.equal(s.hp,160);s.events=[];b.nodeRepair=0;C.specialEnemy(s,b,.01);assert.deepEqual(b.nodes,[150,150]);assert.equal(s.events.filter(e=>e.type==='partsRepaired').length,1);C.specialEnemy(s,b,.01);assert.equal(s.events.filter(e=>e.type==='partsRepaired').length,1);}});

test('固定副砲與地雷不因座標碰巧重合而誤報誘導，主砲仍保留真鎖定',()=>{const s=C.setup(arena(),{tactic:'decoy'});s.x=205;C.useTactic(s);s.x=750;const e=C.spawnSpecial(s,'dinosauria',500,460);C.telegraph(s,e,'secondary',205,260,1.25,24);C.telegraph(s,e,'mine',205,170,.25,32);C.telegraph(s,e,'heavy',205,280,1.3,40);assert.deepEqual(s.hazards.map(h=>h.x),[205,205,205]);assert.deepEqual(s.hazards.map(h=>h.decoyX),[undefined,undefined,205]);});

test('獵兵從初次與退回位置橫跨鎖定點時，不會在未抵達終點前結算衝撞',()=>{for(const y of [330,680]){const s=arena(),c=C.spawnEnemy(s,'charger',110,y);s.shot=s.mg=s.blade=10000;s.x=890;c.dashing=true;c.chargeX=890;run(s,.2,890);assert.equal(c.dashing,true);assert.equal(s.hp,100);}});
test('獵兵鎖定後沿固定直線等速前進，到終點才造成35傷害',()=>{const s=arena(),c=C.spawnEnemy(s,'charger',110,680);s.shot=s.mg=s.blade=10000;s.x=890;c.cooldown=0;C.step(s,.01,890);assert.equal(c.charging>0,true);const windup=s.events.find(e=>e.type==='chargerWindup');assert.deepEqual(windup,{type:'chargerWindup',sourceId:c.id,x:110,y:680,targetX:890,duration:1});c.charging=.01;C.step(s,.01,110);const dash=s.events.find(e=>e.type==='dash');assert.equal(dash.model,'grauwolf');assert.equal(dash.sourceId,c.id);assert.equal(dash.targetX,890);assert.equal(dash.targetY,795);assert.ok(Math.abs(dash.duration-Math.hypot(780,115)/740)<1e-9);const before={x:c.x,y:c.y};C.step(s,.05,890);assert.ok(Math.abs((c.x-before.x)/(c.y-before.y)-780/115)<1e-6);assert.equal(s.hp,100);while(c.dashing)C.step(s,.01,890);assert.equal(c.x,890);assert.equal(c.y,795);assert.equal(s.hp,65);assert.deepEqual(s.events.find(e=>e.type==='chargerBrake'),{type:'chargerBrake',sourceId:c.id,x:890,y:795,hit:true});assert.deepEqual(s.events.find(e=>e.type==='ramHit'),{type:'ramHit',x:890,y:805,source:'charger',sourceId:c.id,model:'grauwolf'});});
test('獵兵鎖定誘餌後不受玩家或新誘餌改向，撲空失衡與反擊時間正確',()=>{const s=C.setup(arena(),{tactic:'decoy'}),c=C.spawnEnemy(s,'charger',110,680);s.shot=s.mg=s.blade=10000;s.x=250;C.useTactic(s);c.cooldown=0;C.step(s,.01,250);assert.equal(c.chargeX,250);assert.equal(c.chargeDecoyX,250);assert.equal(s.events.find(e=>e.type==='chargerWindup').decoyX,250);s.x=890;s.charges=1;s.tacticCooldown=0;C.useTactic(s);c.charging=.01;C.step(s,.01,890);assert.equal(c.chargeX,250);assert.equal(c.chargeDecoyX,250);while(c.dashing)C.step(s,.01,890);assert.equal(c.x,250);assert.equal(c.y,795);assert.deepEqual(s.events.find(e=>e.type==='chargerBrake'),{type:'chargerBrake',sourceId:c.id,x:250,y:795,hit:false});while(c.retreat)C.step(s,.01,890);assert.equal(c.y,650);assert.equal(c.stagger,2.4);const stagger=s.events.find(e=>e.type==='stagger');assert.equal(stagger.sourceId,c.id);assert.equal(stagger.model,'grauwolf');assert.equal(stagger.duration,2.4);const hp=c.hp;C.damageEnemy(s,c,10);assert.equal(c.hp,hp-18);run(s,4.7,890);assert.equal(c.stagger,0);assert.equal(c.charging>0,true);});
test('EMP取消獵兵蓄力或突進並清除舊軌跡',()=>{for(const state of ['charging','dashing']){const s=arena(),c=C.spawnEnemy(s,'charger',110,680);s.shot=s.mg=s.blade=10000;s.x=890;c.cooldown=0;C.step(s,.01,890);if(state==='dashing')run(s,1.01,890);const x=c.x,y=c.y;C.collect(s,{kind:'emp',readable:true,y:815});assert.equal(c.charging,0);assert.equal(c.dashing,false);assert.equal(c.dashDuration,0);run(s,.3,890);assert.equal(c.x,x);assert.equal(c.y,y);}});
test('獵兵撲空會退至主砲口前，桌面砲口高低都可進入反擊',()=>{for(const muzzleY of [610,690]){const s=arena(),c=C.spawnEnemy(s,'charger',500,780);s.shot=s.mg=s.blade=10000;s.x=800;s.muzzleY=muzzleY;c.dashing=true;c.chargeX=500;run(s,.5,800);assert.equal(c.y,Math.min(680,muzzleY-40));assert.ok(c.stagger>0);const hp=c.hp;C.damageEnemy(s,c,10);assert.equal(c.hp,hp-18);}});
test('追獵遭遇一開始有獵兵，後續精英維持獵兵並在50秒進入Dinosauria',()=>{const s=C.setup(arena(),{encounter:'pursuit'});assert.equal(s.elite,8);assert.deepEqual(s.enemies.map(e=>[e.type,e.x,e.y]),[['charger',500,330]]);s.enemies=[];s.elite=0;C.step(s,.01,500);assert.ok(s.enemies.some(e=>e.type==='charger'));s.enemies=[];s.boss=.01;C.step(s,.02,500);assert.ok(s.enemies.some(e=>e.type==='boss'&&e.model==='dinosauria'));});

test('混合戰轉場相對首領擊破計時，不讓快速突破等待固定時間點',()=>{for(const time of [35,75]){const s=C.setup(arena(),{encounter:'mixed'});s.time=time;const b=C.spawnSpecial(s,'dinosauria',500,460);C.damageEnemy(s,b,99999);assert.equal(s.boss,30);assert.equal(s.recovery,5);assert.equal(s.events.find(e=>e.type==='objective').eta,30);assert.equal(s.over,false);}});
test('混合戰首領後提供整備、獵兵與斥候砲車組合，再接第二首領',()=>{const s=C.setup(arena(),{machine:'m4a3',encounter:'mixed'});s.time=40;s.hp=s.maxHp=999;s.shot=s.mg=s.blade=10000;const b=C.spawnSpecial(s,'dinosauria',500,460);C.damageEnemy(s,b,99999);C.step(s,.01,890);assert.deepEqual(s.crates.filter(b=>!b.drop).map(b=>b.kind),['repair','charge']);const group=s.crates[0].group;run(s,6.7,890);assert.equal(s.enemies.filter(e=>e.type==='charger').length,0);run(s,.4,890);assert.equal(s.enemies.filter(e=>e.type==='charger').length,1);run(s,11.2,890);assert.ok(s.enemies.some(e=>e.type==='scout'));assert.ok(s.enemies.some(e=>e.type==='shield'));run(s,11.8,890);assert.ok(s.enemies.some(e=>e.model==='morpho'));assert.ok(s.special<9);assert.ok(s.elite<10);assert.equal(s.crates.some(b=>!b.drop&&b.group!==group),false);});
test('整備補給以 seeded 左右選擇交換修復與戰術充能，且可重現',()=>{const supply=random=>{const s=C.setup(C.create(()=>random),{encounter:'mixed'});s.spawn=s.special=s.elite=s.boss=s.gate=10000;s.regroupSupply=true;s.crate=0;C.step(s,.01,500);return s.crates.filter(b=>!b.drop).map(b=>[b.x,b.kind]);};const left=supply(.1),right=supply(.9);assert.deepEqual(left,[[265,'charge'],[735,'repair']]);assert.deepEqual(right,[[265,'repair'],[735,'charge']]);assert.deepEqual(supply(.1),left);});
test('轉場保留既有威脅且不重複生成獵兵；單Boss遭遇仍直接結算',()=>{const s=C.setup(arena(),{encounter:'mixed'}),c=C.spawnEnemy(s,'charger',300,330),b=C.spawnSpecial(s,'dinosauria',500,460);C.damageEnemy(s,b,99999);s.elite=0;s.recovery=0;s.shot=s.mg=s.blade=10000;C.step(s,.01,800);assert.equal(s.enemies.filter(e=>e.type==='charger').length,1);assert.ok(s.enemies.includes(c));run(s,7,800);assert.equal(s.enemies.filter(e=>e.type==='charger').length,1);assert.equal(s.regroupWave,1);const t=C.setup(arena(),{encounter:'dinosauria'}),d=C.spawnSpecial(t,'dinosauria',500,460);C.damageEnemy(t,d,99999);assert.ok(t.won&&t.over);});
test('首領擊破不覆蓋已展示補給，整備排在原選擇後，獵兵等選取窗口結束',()=>{const s=C.setup(arena(),{machine:'m4a3'});s.shot=s.mg=s.blade=10000;s.crates=[{id:900,group:900,x:265,y:0,kind:'he',readable:true,used:false}];const b=C.spawnSpecial(s,'dinosauria',500,460);C.damageEnemy(s,b,99999);run(s,6.5,500);assert.deepEqual(s.crates.filter(c=>!c.drop).map(c=>c.kind),['he']);run(s,1,500);assert.deepEqual(s.crates.filter(c=>!c.drop).map(c=>c.kind),['repair','charge']);assert.equal(s.enemies.some(e=>e.type==='charger'),false);run(s,6.4,500);assert.equal(s.enemies.filter(e=>e.type==='charger').length,1);});

test('主砲事件與砲彈記錄實際機型、砲口、增幅與傷害',()=>{const s=C.setup(arena(),{machine:'m4a3'});s.x=s.target=500;s.brace=.45;s.shot=0;s.mg=10000;C.step(s,.01,500);const event=s.events.find(e=>e.type==='mainShot'),bullet=s.bullets.find(b=>b.shell&&b.controlled);assert.deepEqual(event,{type:'mainShot',machine:'m4a3',x:500,y:690,boost:'brace',damage:75.735,ammo:'standard'});assert.equal(bullet.boost,'brace');assert.equal(bullet.damage,event.damage);});
test('XM2動能只在實際主砲發射時消耗並標記砲彈',()=>{const s=C.setup(arena(),{machine:'xm2'});s.momentum=100;s.shot=.82;s.mg=1;C.step(s,.01,500);assert.equal(s.momentum,100);assert.equal(s.events.some(e=>e.type==='momentum'),false);s.shot=0;C.step(s,.01,500);const event=s.events.find(e=>e.type==='mainShot'),bullet=s.bullets.find(b=>b.shell&&b.controlled);assert.equal(s.momentum,0);assert.deepEqual({...event,damage:undefined},{type:'mainShot',machine:'xm2',x:500,y:690,boost:'momentum',damage:undefined,ammo:'standard'});assert.ok(Math.abs(event.damage-65.61)<1e-9);assert.equal(bullet.boost,'momentum');});
test('停穩跨越門檻只回報一次，移動解除後可再次回報',()=>{const s=C.setup(arena(),{machine:'m4a3'});s.shot=s.mg=10000;s.brace=.44;C.step(s,.02,500);assert.equal(s.events.filter(e=>e.type==='braceReady').length,1);C.step(s,.02,500);assert.equal(s.events.filter(e=>e.type==='braceReady').length,0);C.step(s,.05,890);assert.equal(s.brace,0);s.brace=.44;s.x=s.target=500;C.step(s,.02,500);assert.equal(s.events.filter(e=>e.type==='braceReady').length,1);});
test('近戰事件保留起點、目標快照與實際耐久損失，且不重打目標',()=>{const s=C.setup(arena(),{machine:'m1a4'}),e=C.spawnEnemy(s,'normal',500,700);s.shot=s.mg=10000;s.muzzleY=630;e.speed=0;e.hp=20;C.step(s,.01,500);const event=s.events.find(e=>e.type==='blade');assert.deepEqual(event,{type:'blade',machine:'m1a4',x:500,y:630,target:{id:e.id,x:500,y:700,kind:'normal',model:null},actualDamage:20,killed:true});assert.equal(e.dead,true);assert.equal(s.kills,1);});
test('主砲命中事件攜帶實際砲彈的增幅標記',()=>{const s=C.setup(arena()),e=C.spawnEnemy(s,'normal',500,500);s.shot=s.mg=10000;e.speed=0;s.bullets=[{x:500,y:505,px:500,py:515,vx:0,damage:10,life:1,left:1,shell:true,boost:'momentum',hit:[]}];C.step(s,.01,500);assert.equal(s.events.find(e=>e.type==='impact').boost,'momentum');});

test('射擊事件保留彈藥並回報直接命中的實際傷害上限',()=>{const s=C.setup(arena(),{ammo:'standard'}),e=C.spawnEnemy(s,'normal',500,500);s.shot=s.mg=10000;e.speed=0;e.hp=7;s.bullets=[{x:500,y:505,px:500,py:515,vx:0,damage:20,life:1,left:1,shell:true,controlled:true,ammo:'standard',hit:[]}];C.step(s,.01,500);const impact=s.events.find(e=>e.type==='impact');assert.deepEqual(impact,{type:'impact',x:500,y:500,kind:'normal',armored:false,boost:'none',shell:true,ammo:'standard',targetId:e.id,damage:7,killed:true,penetrating:false});s.shot=0;s.mg=10000;C.step(s,.01,500);assert.equal(s.events.find(e=>e.type==='mainShot').ammo,'standard');assert.equal(s.bullets.find(b=>b.shell).ammo,'standard');});

test('HE 爆炸只列出本次範圍內實際受傷的目標，邊界不命中',()=>{const s=C.setup(arena(),{ammo:'he'}),direct=C.spawnEnemy(s,'normal',500,500),near=C.spawnEnemy(s,'normal',600,500),edge=C.spawnEnemy(s,'normal',666,500);s.shot=s.mg=10000;for(const e of [direct,near,edge])e.speed=0;direct.hp=5;near.hp=10;s.bullets=[{x:500,y:505,px:500,py:515,vx:0,damage:20,life:1,left:1,shell:true,controlled:true,ammo:'he',he:true,explosive:true,hit:[]}];C.step(s,.01,500);const blast=s.events.find(e=>e.type==='blast');assert.equal(blast.ammo,'he');assert.equal(blast.radius,165);assert.deepEqual(blast.directTarget,{id:direct.id,kind:'normal',model:'normal',x:direct.x,y:direct.y});assert.deepEqual(blast.hits,[{id:near.id,kind:'normal',model:'normal',x:near.x,y:near.y,damage:10,killed:true}]);assert.equal(edge.hp,edge.max);});

test('AP 不產生爆炸，砲座命中與未受傷僚機都回報真實傷害',()=>{const s=C.setup(arena(),{ammo:'ap',encounter:'dinosauria'}),boss=C.spawnSpecial(s,'dinosauria',500,460);s.shot=s.mg=10000;boss.intro=0;boss.nodes[0]=3;s.bullets=[{x:395,y:468,px:395,py:478,vx:0,damage:20,life:1,left:1,shell:true,controlled:true,ammo:'ap',armorPiercing:true,hit:[]}];C.step(s,.01,500);let impact=s.events.find(e=>e.type==='impact');assert.equal(impact.ammo,'ap');assert.equal(impact.targetId,boss.id);assert.equal(impact.damage,3);assert.equal(impact.killed,false);assert.equal(s.events.some(e=>e.type==='blast'),false);boss.nodes[1]=9;s.events=[];s.bullets=[{x:605,y:468,px:605,py:478,vx:0,damage:20,life:1,left:1,shell:true,controlled:false,ammo:'ap',armorPiercing:true,hit:[]}];C.step(s,.01,500);impact=s.events.find(e=>e.type==='impact');assert.equal(impact.damage,0);assert.equal(impact.killed,false);assert.equal(boss.nodes[1],9);});


test('斥候一般標定被擊破不誤報砲兵第二落點取消',()=>{const s=arena(),scout=C.spawnEnemy(s,'scout',500,300);s.hazards=[{source:scout.id,kind:'mark',x:500,fired:false}];C.damageEnemy(s,scout,999);assert.equal(s.hazards.length,0);assert.equal(s.events.some(e=>e.type==='fireLinkBroken'),false);});


test('火力支援開場先展示協同預告，仍可在離膛前擊破砲兵中斷',()=>{const s=C.setup(C.create(()=>.5),{encounter:'fire-support',machine:'m1a4'});s.shot=s.mg=10000;s.spawn=s.special=s.boss=s.elite=s.crate=s.gate=10000;const seen=[];for(let i=0;i<24;i++){C.step(s,1/60,500);seen.push(...s.events);}const aim=seen.find(e=>e.type==='mortarAim');assert.ok(aim);assert.equal(aim.linkedTo,s.enemies.find(e=>e.type==='scout').id);assert.deepEqual(s.hazards.map(h=>h.shotIndex),[0,1]);const artillery=s.enemies.find(e=>e.type==='artillery');assert.equal(artillery.max,150);C.damageEnemy(s,artillery,150);assert.equal(s.hazards.length,0);assert.equal(s.hp,100);});


test('通用彈每發只爆破一次，後續穿透仍造成直擊',()=>{const s=C.setup(arena(),{machine:'m1a4',ammo:'standard'});s.level=4;s.count=1;s.shot=0;s.mg=s.blade=10000;for(const y of [580,500,420]){const e=C.spawnEnemy(s,'shield',500,y);e.cooldown=10000;}const seen=[];C.step(s,.01,500);seen.push(...s.events);s.shot=10000;for(let i=0;i<50;i++){C.step(s,.01,500);seen.push(...s.events);}assert.equal(seen.filter(e=>e.type==='blast').length,1);assert.equal(seen.filter(e=>e.type==='impact').length,3);assert.ok(seen.filter(e=>e.type==='impact').every(e=>e.damage>0));});


test('干擾中遠距直射仍可實際擊中原耐久敵機',()=>{const s=C.setup(arena(),{machine:'m1a4',ammo:'ap'});s.count=1;s.spawn=s.special=s.boss=s.elite=s.crate=s.gate=s.mg=s.blade=10000;s.x=s.target=500;const jammer=C.spawnSpecial(s,'jammer',650,320),target=C.spawnEnemy(s,'shield',500,420),hp=target.hp;target.cooldown=10000;s.shot=0;const events=[];for(let i=0;i<45;i++){C.step(s,1/60,500);events.push(...s.events);s.shot=10000;}assert.equal(s.jammed,true);assert.ok(!s.fireControl[0].target);assert.ok(target.hp<hp);assert.ok(events.some(e=>e.type==='impact'&&e.targetId===target.id&&e.damage>0));assert.equal(jammer.hp,90);});

test('普通兵接近後有限轉向追蹤，玩家換側時不瞬間反轉',()=>{const s=arena(),e=C.spawnEnemy(s,'normal',180,500);s.shot=s.mg=s.blade=10000;run(s,.5,820);assert.ok(e.x>180);assert.ok(e.lateral>0&&e.lateral<=90);const before=e.x;C.step(s,.05,110);assert.ok(e.x>before);assert.ok(e.lateral>0);});

test('混合戰前段與首領後整備延長為可讀遭遇窗口',()=>{const s=C.setup(arena(),{encounter:'mixed'});assert.equal(s.boss,46);const b=C.spawnSpecial(s,'dinosauria',500,460);C.damageEnemy(s,b,99999);assert.equal(s.boss,30);assert.equal(s.events.find(e=>e.type==='objective').eta,30);});

test('擊毀事件提供穩定演出識別且不攜帶步態形狀快照',()=>{const s=arena(),elite=C.spawnEnemy(s,'charger',420,360);C.damageEnemy(s,elite,99999);const kill=s.events.find(e=>e.type==='kill'),down=s.events.find(e=>e.type==='eliteDown');assert.deepEqual(kill,{type:'kill',sourceId:elite.id,kind:'charger',model:'charger',x:elite.x,y:elite.y});assert.deepEqual(down,{type:'eliteDown',sourceId:elite.id,kind:'charger',model:'charger',x:elite.x,y:elite.y});});

test('無限模式交替首領且擊破兩隻仍繼續下一輪',()=>{const s=C.setup(arena(),{encounter:'mixed',mode:'endless'});assert.equal(s.mode,'endless');assert.equal(s.wave,1);for(const model of ['dinosauria','morpho']){const b=C.spawnSpecial(s,model,500,460);C.damageEnemy(s,b,99999);assert.equal(s.over,false);assert.equal(s.won,false);assert.equal(s.boss,30);s.enemies=[];s.recovery=0;s.boss=.01;C.step(s,.02,500);assert.equal(s.enemies.find(e=>e.type==='boss').model,model==='dinosauria'?'morpho':'dinosauria');s.enemies=[];}assert.equal(s.wave,3);assert.equal(s.maxHp,100);});

test('死亡結果保留模式與波次，重新設定可保持無限模式',()=>{const s=C.setup(arena(),{mode:'endless'});s.wave=4;s.count=1;s.hp=30;C.hurt(s,999,true,{kind:'contact',model:'normal'});const result=C.result(s);assert.equal(result.mode,'endless');assert.equal(result.wave,4);const retry=C.setup(C.create(()=>.5),{mode:result.mode});assert.equal(retry.mode,'endless');assert.equal(retry.wave,1);});

test('無限模式不暗依賴遭遇選項，直接選Morpho仍由Dinosauria首波開始',()=>{const s=C.setup(arena(),{mode:'endless',encounter:'morpho'});assert.equal(s.boss,46);s.boss=.01;s.recovery=0;C.step(s,.02,500);const boss=s.enemies.find(e=>e.type==='boss');assert.equal(boss.model,'dinosauria');});
